### ISSUE TITLE
Documentation is incorrect

### ISSUE THREAD

**Issue by Ventajou** [kaelzhang/node-scaffold-generator#7]
Hi,

I'm looking to use this module in a simple command line utility. I was following the documentation only to find out that the `generate` function does not exist... Could you please fix the documentation?

**Comment by kaelzhang** [comment]
Sorry I'm late.

`scaffold.generate()` had been changed to `scaffold.copy()` method.

```js
scaffold(options).copy('/path/from', '/path/to', callback)
scaffold(options).copy({
  '/path/from1': '/path/to1',
  '/path/from2': '/path/to2'
}, callback)
```
